#!/usr/bin/env bash
set -e  # exit on error

IMAGE_NAME="ghcr.io/shortestpathlab/opss25-startkit:latest"

# Get current working directory (where script is run from)
CURRENT_DIR=$(pwd)

# Run container, mount current dir, and pass through all script args
sudo docker run --pull always --rm \
  -v "$CURRENT_DIR":/data \
  -w /data \
  $IMAGE_NAME "$@"
