#!/usr/bin/env bash
set -e  # exit on error

# IMAGE_NAME="ghcr.io/shortestpathlab/opss25-startkit:latest"
IMAGE_NAME="hello-world"

# Get current working directory (where script is run from)
CURRENT_DIR=$(pwd)

# Run hello-world container, mount current dir, and pass through all script args
docker run --rm \
  -v "$CURRENT_DIR":/data \
  $IMAGE_NAME "$@"
