#!/usr/bin/env bash
set -e  # exit on error

echo "⚠️  WARNING: This will delete the ~/opss25 directory and all its contents. Type Y to continue, or Ctrl-C to cancel."
read -r -p "Continue? " response
if [[ $response =~ ^([Yy]|yes|Yes|YES) ]]
then
    echo "Proceeding..."
    rm -rf ~/opss25
else
    echo "Aborting"
    exit 1
fi
